# This is the RoboClerk configuration file

# Provide the name of the file provider plugin. The default is the LocalFileProviderPlugin 
# that assumes files are being read off of the local filesystem. The other is the
# SharePointFileProviderPlugin if the files are hosted in a sharepoint library.

FileProviderPlugin = "LocalFileProviderPlugin"

# RoboClerk will search for plugins in the subdirectories of the plugin dirs.
# For example: PluginDirs = [ "c:/temp/plugins" ]. Note that the plugins are included
# with the RoboClerk container, so when using the container, this should point to
# /home/RoboClerk/plugins

PluginDirs = [ "{PLUGINROOT}/plugins" ]

# The configuration files for the plugins may be in a different location than the 
# plugins themselves. E.g. when executing RoboClerk in a docker environment. If
# the following configuration item is empty, then the standard location 
# in the Configuration subdir of the plugins directory is assumed.

PluginConfigurationDir = "{DOCUMENTATIONROOT}RoboClerk_input/PluginConfig"

# Clear output directory before creating new output files.

ClearOutputDir = "True"

# Logging level (DEBUG, INFO or WARN)

LogLevel = "WARN"

# Output format (ASCIIDOC, HTML or DOCX)

OutputFormat = "{OUTPUTFORMAT}"